Update peer dependency eslint-plugin-n to v16
standard/eslint-config-standard-with-typescript pull request #1143
Opened 2023-05-23 20:25 UTC by CCFenner

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
update peer dependency

**Which issue (if any) does this pull request address?**
#1142 

**Is there anything you'd like reviewers to focus on?**

2023-05-29 20:03 UTC, falsepopsky requested changes
It's required to first update `eslint-config-standard` to the new version `17.1.0`

2023-05-29 20:03 UTC, falsepopsky commented on package.json
> +    "eslint-plugin-n": "^16.0.0",
```suggestion
    "eslint-plugin-n": "^15.0.0 || ^16.0.0 ",
```

https://github.com/standard/eslint-config-standard/blob/master/package.json

2023-07-07 05:27 UTC, mightyiam commented
Thank you for this, @CCFenner. This bump should go together with bumping esling-config-standard. In fact, I wonder why no tests failed...

2023-07-15 07:23 UTC, mightyiam commented
Thank you for you effort, @CCFenner . This took some more work, so we did this ourselves. Enjoy.

2023-07-15 07:23 UTC, closed without merging